on:
  push: 
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      backboneName:
        description: 'Name of Clusters to Delete'
        required: true
        type: string


jobs:
  log-the-inputs:
    name: "logging the inputs"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#/refs/heads} | tr / -)" >> $GITHUB_ENV

      - name: Override Branch Name
        if: "${{ github.event.inputs.backboneName != '' }}"
        run: echo "BRANCH_NAME=${{ inputs.backboneName }}" >> $GITHUB_ENV
      - run: |
          echo "${{ env.BRANCH_NAME }}"