on:
  release:
    types: [published]

jobs:
  build:
    name: TTCS Release Build and Upload
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Release Version
        if: github.event_name == 'release'
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RELEASE_VERSION_TEST=2" >> $GITHUB_ENV
          echo "RELEASE_FOLDER=files/*" >> $GITHUB_ENV

      - name: Echo Release
        run: |
          echo "${{ env.RELEASE_VERSION_TEST }}"

      - uses: mxschmitt/action-tmate@v3

      - name: Truncate Release URL
        run: |
          echo "RELEASE_URL=$(echo "${{ github.event.release.upload_url }}" | sed 's/{.*//' )" >> $GITHUB_ENV

      - name: Upload all the files in TTCS Release to Github
        run: |
          for FILE in ${{ env.RELEASE_FOLDER }}
          do
            ASSET_NAME=$(basename $FILE)
            echo $ASSET_NAME
            CONTENT_TYPE=$(file -b --mime-type $FILE)
            echo $CONTENT_TYPE
            curl \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type":$CONTENT_TYPE \
              --data-binary @$FILE \
              "${{ env.RELEASE_URL }}?name=$ASSET_NAME"
          done 