name: My Workflow

on:
  release:
    types: [ published ]
jobs:
  my-job:
    runs-on: [ my-runner ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
       
      - name: Test
        run: |
          echo "test"