on:
  release:
    types: [published]

jobs:
  release-project:
    - name: Get Release Version
    if: github.event_name == 'release'
      run: |
        echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "${GITHUB_WORKSPACE}/bazel-bin/clocksync/packages/deb9/ttcs-agent_${{ env.VERSION }}_amd64.deb"
        asset_name: "ttcs-agent_${{ env.VERSION }}_amd64.deb"
        asset_content_type: application/vnd.debian.binary-package
        