on:
  release:
    types: [published]

jobs:
  my-job:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Get Release Version
        if: github.event_name == 'release'
        run: |
          echo "VERSION=$(echo ${GITHUB_REF#refs/*/} | sed 's/^.*v//')" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "./ttcs-agent_${{ env.VERSION }}_amd64.deb"
          asset_name: "ttcs-agent_${{ env.VERSION }}_amd64.deb"
          asset_content_type: application/vnd.debian.binary-package
