on:
  release:
    types: [published]

jobs:
  log-the-inputs:
    name: "logging the inputs"
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#/refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Override Branch Name
        if: "${{ github.event.inputs.backboneName != '' }}"
        run: echo "BRANCH_NAME=${{ inputs.backboneName }}" >> $GITHUB_ENV
      - name: Echo Branch Name
        run: echo "${{ env.BRANCH_NAME }}"
      - name: Test
        run: echo "testing"