name: My Workflow

on:
  release:
    types: [published]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
       
      - name: Test
        run: |
          echo "test"